### ISSUE TITLE
Support for xlink:href attribute

### ISSUE THREAD

**Issue by Frenzzy** [janjakubnanista/svg-to-jsx#1]
Since version 0.14 (facebook/react/pull/3704) React allows to use the namespaced attributes: 
> https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html
> React DOM now supports these SVG attributes, which render into namespaced attributes: `xlinkActuate`, `xlinkArcrole`, `xlinkHref`, `xlinkRole`, `xlinkShow`, `xlinkTitle`, `xlinkType`, `xmlBase`, `xmlLang`, `xmlSpace`.

It would be great to add support for all the available jsx attributes:
https://github.com/facebook/react/blob/master/src/renderers/dom/shared/SVGDOMPropertyConfig.js

**Comment by janjakubnanista** [comment]
Thanks @Frenzzy! I will add that ASAP.

**Comment by janjakubnanista** [comment]
Fixed in 0.0.10

**Comment by Frenzzy** [comment]
Cool, thanks! Don't forget to update readme ;)
