### ISSUE TITLE
Does not convert to JSX?

### ISSUE THREAD

**Issue by lemoustachiste** [janjakubnanista/svg-to-jsx#10]
Hi, 

I followed the instructions to run in the command line, however the output remains the SVG, and I don't understand why.

for instance, if I run the command without the output flag:
`./node_modules/.bin/svg-to-jsx src/icons/icon-add.svg`

This is what I get in the terminal:
```
<svg height="46px" width="47px" version="1.1" viewBox="0 0 47 46">
	<defs/>
	<g id="Search-Components" fillRule="evenodd" stroke="none" strokeWidth="1">
		<g id="Search_Inactive" transform="translate(-332.000000, -154.000000)">
			<g id="center" transform="translate(270.000000, 87.000000)">
				<g id="add-new">
					<path id="add-icon" d="M91,95 L91,113 L80,113 L80,95 L62,95 L62,85 L80,85 L80,67 L91,67 L91,85 L109,85 L109,95 L91,95 Z"/>
				</g>
			</g>
		</g>
	</g>
</svg>
```

If I run the bash script, I do get `.jsx` files generated where I want to, but they also are still SVGs inside.

```
#!/usr/bin/env bash
targetDirectory=lib/svgComponents
rm -rf $targetDirectory
mkDir $targetDirectory
for file in src/icons/*
do
    fileName=$(basename $file .svg)
    echo $fileName
    #whatever you need with "$file"
    svg-to-jsx -o $targetDirectory/$fileName.jsx $file
done
```

So it seems I am missing something silly?

**Comment by janjakubnanista** [comment]
Hi @lemoustachiste!

The output is correct, i you look at the first example you provided you can see that the SVG attributes have been converted to JSX attributes:

    stroke-width => strokeWidth
    fill-rule => fillRule

etc.

You can now use this output in your components' render() methods.
