### ISSUE TITLE
undefined on output jsx file

### ISSUE THREAD

**Issue by juancabrera** [janjakubnanista/svg-to-jsx#2]
I have this SVG: https://infinit.io/_/dCjuCUR

When I run `svg-to-jsx -o usa-map-ids.svg.jsx usa-map-ids.svg` all the content of the `usa-map-ids.svg.jsx` file is `undefined`

**Comment by janjakubnanista** [comment]
Thanks for reporting this @juancabrera! I will take a look and see what's causing this.

**Comment by janjakubnanista** [comment]
Fixed by [80f6275f68db491263dab847aecc100d9f8e755b](https://github.com/janjakubnanista/svg-to-jsx/commit/80f6275f68db491263dab847aecc100d9f8e755b) in version 0.0.11
