### ISSUE TITLE
Support for image tag

### ISSUE THREAD

**Issue by ludamad** [janjakubnanista/svg-to-jsx#4]
With React 0.14 supporting the image tag, it feels prudent to support it here as well, lest someone forks simply to do so.

**Comment by janjakubnanista** [comment]
Hi @ludamad! I will get back to you tomorrow with a fix for this.

**Comment by ludamad** [comment]
Thanks. For the time being I was able to simply edit the source to include image in the allowed tags for my needed.

**Comment by janjakubnanista** [comment]
I was checking support for this and and I am not sure if `<img/>` tags are actually valid SVG elements. Could you provide an example @ludamad? Thanks!

**Comment by ludamad** [comment]
The <image> tag, not the <img> tag.

**Comment by janjakubnanista** [comment]
Fixed in version `0.0.14`. Thanks @ludamad!
