### ISSUE TITLE
camelCased tags seem to loose their camelcasing

### ISSUE THREAD

**Issue by BenevolentNeko** [janjakubnanista/svg-to-jsx#6]
This might be a problem with node-xml2js, but I think there should be some tests for how the output is working for tags such as `<linearGradient>` which is getting parsed into `<lineargradient>` and thus not working.

Thanks.

**Comment by janjakubnanista** [comment]
@BenevolentNeko thanks for the feedback! I will add some tests and fix the bug as soon as I am done with a release at work.

**Comment by lifeiscontent** [comment]
@janjakubnanista seems to be an issues with attributes that are dasherize like `stroke-width` that don't get converted to `strokeWidth`

**Comment by orrybaram** [comment]
Hi! Im getting the same issue with `linearGradient` being converted to `lineargradient` any update on this?
